"use client";
import { useEffect,useRef,useState } from "react";
const {extractYouTubeId}=require("../lib/youtube");
const EMOJIS=["❤️","😂","😮","👏","🔥"]; const URL_PATTERN=/(https?:\/\/[^\s]+)/i;
function mergeMessages(prev,incoming){const map=new Map(prev.map(m=>[m.messageId||m.clientId||`${m.username}:${m.at}:${m.message}`,m]));incoming.forEach(m=>{if(m.type==="system")return;const x={type:"message",messageId:m.messageId||m.id,userId:m.userId||m.user_id,username:m.username,message:m.message,clientId:m.clientId||m.client_id,at:m.at||m.created_at};map.set(x.messageId||x.clientId||`${x.username}:${x.at}:${x.message}`,x);});return [...map.values()].sort((a,b)=>Number(a.at||0)-Number(b.at||0)).slice(-200);}
export default function Chat({channel,broadcast,username,participants,onAddToQueue,roomCode}){
 const[messages,setMessages]=useState([]),[input,setInput]=useState(""),[showParticipants,setShowParticipants]=useState(false),[sending,setSending]=useState(false),[chatError,setChatError]=useState("");const endRef=useRef(null),messagesRef=useRef(null);
 useEffect(()=>{if(!roomCode)return;let cancelled=false;const load=async()=>{try{const r=await fetch(`/api/rooms/${roomCode}/messages`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();if(!cancelled&&Array.isArray(d.messages))setMessages(prev=>mergeMessages(prev,d.messages));}catch{}};load();const t=setInterval(load,2500);return()=>{cancelled=true;clearInterval(t)};},[roomCode]);
 useEffect(()=>{if(!channel)return;const onMessage=m=>setMessages(prev=>mergeMessages(prev,[m]));const onAdded=m=>setMessages(prev=>[...prev,{type:"system",text:`${m.info?.username||"Someone"} joined the room`,at:Date.now()}]);const onRemoved=m=>setMessages(prev=>[...prev,{type:"system",text:`${m.info?.username||"Someone"} left the room`,at:Date.now()}]);channel.bind("chat:message",onMessage);channel.bind("pusher:member_added",onAdded);channel.bind("pusher:member_removed",onRemoved);return()=>{channel.unbind("chat:message",onMessage);channel.unbind("pusher:member_added",onAdded);channel.unbind("pusher:member_removed",onRemoved)};},[channel]);
 useEffect(()=>{
  const box=messagesRef.current;
  if(!box)return;
  const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<120;
  if(nearBottom)box.scrollTop=box.scrollHeight;
},[messages]);
 async function sendMessage(e){e.preventDefault();const text=input.trim();if(!text||sending)return;setSending(true);setChatError("");const clientId=crypto.randomUUID?.()||Math.random().toString(36).slice(2);try{const r=await fetch(`/api/rooms/${roomCode}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,clientId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Message could not be sent");setMessages(prev=>mergeMessages(prev,[d.data||{message:text,username,clientId,at:Date.now()}]));setInput("");}catch(error){setChatError(error.message||"Message could not be sent");}finally{setSending(false)}}
 return <div className="flex flex-col h-full bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden"><button onClick={()=>setShowParticipants(s=>!s)} className="px-4 py-3 border-b border-neutral-800 text-sm text-neutral-400 text-left">{participants.length} watching <span className="text-neutral-600">· {showParticipants?"hide":"show"} list</span></button>{showParticipants&&<div className="px-4 py-2 border-b border-neutral-800 space-y-1.5 max-h-40 overflow-y-auto">{participants.map(p=><div key={p.id} className="flex justify-between text-xs"><span>{p.username}</span>{p.isHost&&<span className="text-[9px] uppercase text-accent">Host</span>}</div>)}</div>}<div ref={messagesRef} className="flex-1 overflow-y-auto px-4 py-3 space-y-2 text-sm">{messages.map((m,i)=>m.type==="system"?<p key={`s-${i}`} className="text-xs text-neutral-500 italic">{m.text}</p>:<div key={m.messageId||m.clientId||i}><p><span className="text-accent font-medium">{m.username}: </span><span className="text-neutral-200">{m.message}</span></p>{(()=>{const u=String(m.message||"").match(URL_PATTERN);const y=u?extractYouTubeId(u[1]):null;return y?<button onClick={()=>onAddToQueue?.(u[1])} className="mt-1 text-xs px-2.5 py-1 rounded-full bg-neutral-800 text-neutral-300">➕ Add to queue</button>:null})()}</div>)}<div ref={endRef}/></div>{chatError&&<div className="px-4 py-2 text-xs text-red-300 border-t border-red-400/10">{chatError}</div>}<div className="px-4 py-2 flex gap-2 border-t border-neutral-800">{EMOJIS.map(e=><button key={e} onClick={()=>broadcast?.("reaction:show",{emoji:e})} className="text-lg">{e}</button>)}</div><form onSubmit={sendMessage} className="p-3 border-t border-neutral-800 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Say something..." className="flex-1 bg-neutral-950 border border-neutral-800 rounded-lg px-3 py-1.5 text-sm"/><button disabled={sending} className="px-3 py-1.5 bg-accent rounded-lg text-sm disabled:opacity-50">{sending?"…":"Send"}</button></form></div>;
}
