"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Nav from "../../components/Nav";

const DEFAULTS = { emailNotifications:true, roomInvites:true, chatNotifications:true, autoplay:true, theme:"velvet" };
const THEMES = [
  {id:"velvet", name:"Velvet Palace", desc:"Warm burgundy, brass accents, and soft cinema glow.", tone:"velvet"},
  {id:"noir", name:"Film Noir", desc:"Deep charcoal, cool silver, and a restrained studio look.", tone:"noir"},
  {id:"olive", name:"Olive In", desc:"Earthy olive tones for a quieter, natural screening room.", tone:"olive"},
  {id:"midnight", name:"Midnight Reel", desc:"Cool midnight blue with subtle violet highlights.", tone:"midnight"},
];

export default function SettingsPage(){
 const router=useRouter(),fileRef=useRef(null);
 const [user,setUser]=useState(null),[form,setForm]=useState({username:"",email:""});
 const [settings,setSettings]=useState(DEFAULTS),[avatar,setAvatar]=useState("");
 const [tab,setTab]=useState("Profile"),[notice,setNotice]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [passwords,setPasswords]=useState({currentPassword:"",newPassword:""});
 const [deletePassword,setDeletePassword]=useState(""),[deleteConfirmation,setDeleteConfirmation]=useState(""),[deleting,setDeleting]=useState(false);

 useEffect(()=>{fetch("/api/auth/profile").then(async r=>{const d=await r.json();if(!r.ok)return router.push("/login?redirect=/settings");const next={...DEFAULTS,...(d.user.settings||{})};setUser(d.user);setForm({username:d.user.username,email:d.user.email});setSettings(next);setAvatar(d.user.avatar_url||"");applyTheme(next.theme);}).catch(()=>router.push("/login?redirect=/settings"));},[router]);
 function applyTheme(theme){if(typeof document!=="undefined"){document.documentElement.dataset.wtTheme=theme||"velvet";localStorage.setItem("wt_theme",theme||"velvet");}}
 function updateTheme(theme){setSettings(s=>({...s,theme}));applyTheme(theme);setNotice("");setError("");}
 async function saveSettings(nextSettings=settings, message="Settings saved."){setSaving(true);setNotice("");setError("");const r=await fetch("/api/auth/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,settings:nextSettings,avatarUrl:avatar||null})});const d=await r.json();setSaving(false);if(!r.ok)return setError(d.error||"Unable to save settings");setUser(d.user);setSettings({...DEFAULTS,...(d.user.settings||nextSettings)});setNotice(d.devVerificationUrl?`Saved. Dev verification link: ${d.devVerificationUrl}`:d.emailChanged?"Saved. Please verify your new email address.":message);}
 async function saveProfile(){await saveSettings(settings,"Profile saved.");}
 async function saveAppearance(){await saveSettings(settings,"Appearance saved.");}
 async function resend(){setNotice("");setError("");const r=await fetch("/api/auth/resend-verification",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:user.email})});const d=await r.json();if(!r.ok)return setError(d.error||"Unable to send verification email");setNotice(d.devVerificationUrl?`Dev verification link: ${d.devVerificationUrl}`:"Verification email sent. Check your inbox.");}
 async function changePassword(){setNotice("");setError("");const r=await fetch("/api/auth/password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(passwords)});const d=await r.json();if(!r.ok)return setError(d.error||"Unable to update password");setPasswords({currentPassword:"",newPassword:""});setNotice("Password updated successfully.");}
 async function uploadAvatar(file){if(!file)return;if(file.size>2*1024*1024)return setError("Avatar must be smaller than 2 MB.");const fd=new FormData();fd.append("file",file);const r=await fetch("/api/auth/avatar",{method:"POST",body:fd});const d=await r.json();if(!r.ok)return setError(d.error||"Unable to upload avatar");setAvatar(d.url);setNotice("Avatar uploaded. Save your profile to keep the change.");}
 if(!user)return <main className="wt-page"><Nav/><div className="wt-shell py-24 text-white/40">Loading settings…</div></main>;
 const initial=user.username?.slice(0,1).toUpperCase()||"U";
 const navTabs=["Profile","Notifications","Appearance","Security"];
 return <main className="wt-page"><Nav username={user.username} avatarUrl={avatar}/><div className="settings-shell wt-shell py-10 max-w-[1100px]">
   <div className="settings-page-head"><p className="eyebrow">ACCOUNT</p><h1 className="font-display text-5xl mt-2">Settings</h1><p>Manage your profile, identity, avatar, notification preferences, theme, and account security.</p></div>
   <div className="settings-layout"><aside className="settings-sidebar">{navTabs.map(x=><button key={x} onClick={()=>{setTab(x);setNotice("");setError("")}} className={`settings-tab ${tab===x?"settings-tab-active":""}`}><span className={`settings-nav-dot ${tab===x?"on":""}`}></span>{x}</button>)}</aside>
   <section className="settings-content wt-card">
    {tab==="Profile"&&<><div className="settings-section-head"><div><p className="eyebrow">PROFILE</p><h2>Profile details</h2><p>Your name and email are used across rooms, invitations, and notifications.</p></div></div><div className="settings-form-block"><label className="settings-label">Full name<input className="wt-input mt-2" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label className="settings-label">Email address<div className="relative"><input className="wt-input mt-2 pr-24" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><span className={`verify-badge ${user.email_verified?"verify-ok":"verify-warn"}`}>{user.email_verified?"Verified":"Unverified"}</span></div></label><button disabled={saving} onClick={saveProfile} className="wt-button wt-button-primary mt-4">{saving?"Saving…":"Save profile"}</button></div><div className="settings-divider"/><div className="settings-section-head"><div><p className="eyebrow">PROFILE AVATAR</p><h2>Profile avatar</h2><p>Show a recognizable image beside your name throughout WatchTogether.</p></div></div><div className="settings-avatar-row"><div className="settings-avatar">{avatar?<img src={avatar} alt="Avatar"/>:initial}</div><div><p className="font-medium">Upload an avatar</p><p className="text-xs text-white/35 mt-1">JPG, PNG, or WebP. Maximum file size is 2 MB.</p><div className="flex gap-2 mt-3"><button className="wt-button wt-button-ghost" onClick={()=>fileRef.current?.click()}>Upload avatar</button>{avatar&&<button className="wt-button wt-button-danger" onClick={()=>setAvatar("")}>Remove</button>}</div><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadAvatar(e.target.files?.[0])}/></div></div>{!user.email_verified&&<div className="verify-callout mt-6"><div><p className="font-medium">Your email is not verified</p><p className="text-xs text-white/40 mt-1">Verify it to keep your account secure.</p></div><button className="wt-button wt-button-primary" onClick={resend}>Resend email</button></div>}{notice&&<p className="settings-success">{notice}</p>}{error&&<p className="settings-error">{error}</p>}</>}
    {tab==="Notifications"&&<><div className="settings-section-head"><div><p className="eyebrow">NOTIFICATIONS</p><h2>Notification preferences</h2><p>Choose which activity should reach you outside the room.</p></div></div><PreferenceList settings={settings} setSettings={setSettings} items={[["emailNotifications","Email notifications","Important account and room updates"],["roomInvites","Room invitations","Notify me when someone invites me to a screening"],["chatNotifications","Chat notifications","Alerts for room activity"]]}/><button disabled={saving} onClick={()=>saveSettings(settings,"Notification preferences saved.")} className="wt-button wt-button-primary mt-5">{saving?"Saving…":"Save preferences"}</button>{notice&&<p className="settings-success">{notice}</p>}{error&&<p className="settings-error">{error}</p>}</>}
    {tab==="Appearance"&&<><div className="settings-section-head"><div><p className="eyebrow">APPEARANCE</p><h2>Theme</h2><p>Choose how WatchTogether looks. The change applies immediately.</p></div></div><div className="theme-grid">{THEMES.map(t=><button key={t.id} onClick={()=>updateTheme(t.id)} className={`theme-card theme-${t.tone} ${settings.theme===t.id?"theme-selected":""}`}><div className="theme-preview"><span></span><i></i><b></b></div><div className="theme-card-copy"><div><strong>{t.name}</strong><small>{t.desc}</small></div><span className="theme-radio">{settings.theme===t.id?"✓":""}</span></div></button>)}</div><div className="theme-save-row"><span>Selected theme: <b>{THEMES.find(t=>t.id===settings.theme)?.name||"Velvet Palace"}</b></span><button disabled={saving} onClick={saveAppearance} className="wt-button wt-button-primary">{saving?"Saving…":"Save appearance"}</button></div>{notice&&<p className="settings-success">{notice}</p>}{error&&<p className="settings-error">{error}</p>}</>}
    {tab==="Security"&&<><div className="settings-section-head"><div><p className="eyebrow">SECURITY</p><h2>Change password</h2><p>Use a strong password you do not reuse elsewhere.</p></div></div><div className="settings-form-block"><label className="settings-label">Current password<input className="wt-input mt-2" type="password" value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label className="settings-label">New password<input className="wt-input mt-2" type="password" value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></label><button className="wt-button wt-button-primary mt-4" onClick={changePassword}>Update password</button></div><div className="settings-divider"/><div className="settings-danger-zone"><div className="settings-section-head"><div><p className="eyebrow text-red-300/80">DANGER ZONE</p><h2>Delete account</h2><p>This permanently removes your WatchTogether account, library videos, rooms you host, notifications, and account settings. This cannot be undone.</p></div></div><div className="settings-form-block"><label className="settings-label">Current password<input className="wt-input mt-2" type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)} autoComplete="current-password"/></label><label className="settings-label">Type <b>DELETE MY ACCOUNT</b> to confirm<input className="wt-input mt-2" value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} placeholder="DELETE MY ACCOUNT" autoComplete="off"/></label><button disabled={deleting||deleteConfirmation.trim().toUpperCase()!=="DELETE MY ACCOUNT"||!deletePassword} className="wt-button wt-button-danger mt-4" onClick={async()=>{setNotice("");setError("");if(!confirm("Delete your WatchTogether account permanently? This cannot be undone."))return;setDeleting(true);const r=await fetch("/api/auth/account",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:deletePassword,confirmation:deleteConfirmation})});const d=await r.json().catch(()=>({}));setDeleting(false);if(!r.ok)return setError(d.error||"Could not delete your account");router.replace("/login?deleted=1");}}> {deleting?"Deleting account…":"Delete account"}</button></div></div>{notice&&<p className="settings-success">{notice}</p>}{error&&<p className="settings-error">{error}</p>}</>}
   </section></div></div></main>;
}
function PreferenceList({settings,setSettings,items}){return <div className="preference-list">{items.map(([key,title,desc])=><label key={key} className="preference-row"><div><p className="font-medium">{title}</p><p className="text-xs text-white/35 mt-1">{desc}</p></div><input type="checkbox" checked={!!settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/></label>)}</div>}
